"""Alert data models."""
from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class AlertSeverity(StrEnum):
    """Severity levels for alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(BaseModel):
    """An alert generated by an alert rule.

    Attributes:
        alert_id: Unique short identifier for the alert.
        severity: How severe the alert is.
        title: Brief summary of the alert.
        message: Detailed description.
        agent_id: Optional agent that triggered the alert.
        rule_name: Name of the rule that generated this alert.
        timestamp: When the alert was generated (UTC).
        metadata: Arbitrary extra context.
    """

    alert_id: str = Field(default_factory=lambda: uuid4().hex[:12])
    severity: AlertSeverity
    title: str
    message: str
    agent_id: str | None = None
    rule_name: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)
